baseURL = 'https://thearticulatemagazine.github.io/vol1/'
languageCode = 'en-us'
googleAnalytics = "G-N54177R5WN"
title = 'The Articulate'
description = "Wings to your creative ambitions, Winds to your artistic journeys"
ignorefiles = [ "docs/.*", "src/.*" ]
enableRobotsTXT = true
summaryLength = 40
cleanDestinationDir = true
enableEmoji = true
newContentEditor = "vscodium"
copyright = "2023 Dr. Rizwan Ishak All rights reserved"
[params]
    email = "gmcrmagazine@gmail.com"
[permalinks]
  posts = '/posts/:filename/'
[minify]
  minifyOutput = true
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
[security.exec]
    allow = ['^vscodium$', '^nvim$', '^code$', '^postcss$'] 