baseURL = 'https://gmcrmagazine.github.io/vol1/'
languageCode = 'en-us'
title = 'The Articulate'
ignorefiles = [ "docs/.*", "src/.*" ]
enableRobotsTXT = true
summaryLength = 40
cleanDestinationDir = true
enableEmoji = true
newContentEditor = "vscodium"
copyright = "2023 Dr. Rizwan Ishak All rights reserved"
[params]
    dateFormat = "02-01-06 15:04"
[permalinks]
  posts = '/posts/:filename/'
[minify]
  minifyOutput = true
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
[security.exec]
    allow = ['^vscodium$', '^nvim$', '^code$', '^postcss$'] 